name: Read Values
on : 
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Name the environment to read'
        required: true
        options:
          - TST
jobs:
  read-value-job:
    runs-on: ubuntu-slim
    environment: ${{github.event.inputs.environment}}
    steps:
      - name: read value
        env:
          MY_VALUE: ${{secrets.SECRET1}}
        run: echo "MY_SECRET" | base64
