name: Read Values
on : 
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Name the environment to read'
        required: true
        options:
          - TST
      readvalue:
        type: string
        description: 'Provide the value to read'
        required: true
jobs:
  read-value-job:
    runs-on: ubuntu-slim
    permissions: read-all
    environment: ${{github.event.inputs.environment}}
    steps:
      - name: read value
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          SECRET_TO_FETCH: ${{github.event.inputs.readvalue}}
        run: |
          VALUE=$(gh secret set-env "$SECRET_TO_FETCH" --env-file /dev/stdout)
          gh secret list
